package interfaces.panelOpciones;

import com.clases.SystemManager;
import interfaces.administracion.BloquearHabitaciones;

public class PanelAdministracion extends javax.swing.JPanel {

    /**
     * Creates new form PanelAdministracion
     */
    public PanelAdministracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFacturacion = new javax.swing.JPanel();
        bloquearHabitaciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFacturacion.setBackground(new java.awt.Color(80, 105, 140));

        bloquearHabitaciones.setText("Bloquear habitaciones");
        bloquearHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloquearHabitacionesActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRACION");

        javax.swing.GroupLayout panelFacturacionLayout = new javax.swing.GroupLayout(panelFacturacion);
        panelFacturacion.setLayout(panelFacturacionLayout);
        panelFacturacionLayout.setHorizontalGroup(
            panelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturacionLayout.createSequentialGroup()
                .addGroup(panelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bloquearHabitaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFacturacionLayout.setVerticalGroup(
            panelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturacionLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bloquearHabitaciones)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        add(panelFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bloquearHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloquearHabitacionesActionPerformed
        BloquearHabitaciones frame = new BloquearHabitaciones();
        frame.setVisible(true);
        
    }//GEN-LAST:event_bloquearHabitacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bloquearHabitaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelFacturacion;
    // End of variables declaration//GEN-END:variables
}
