/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.panelOpciones;

import com.clases.SystemManager;
import interfaces.administracion.BloquearHabitaciones;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Lucas
 */
public class PanelAdministracion extends javax.swing.JPanel {

    /**
     * Creates new form PanelAdministracion
     */
    public PanelAdministracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFacturacion = new javax.swing.JPanel();
        bloquearHabitaciones = new javax.swing.JButton();
        reservasAniadirCargo = new javax.swing.JButton();
        reservasQuitarCargo = new javax.swing.JButton();
        reservasCobroParcial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFacturacion.setBackground(new java.awt.Color(80, 105, 140));

        bloquearHabitaciones.setText("Bloquear habitaciones");
        bloquearHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bloquearHabitacionesMouseClicked(evt);
            }
        });
        bloquearHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloquearHabitacionesActionPerformed(evt);
            }
        });

        reservasAniadirCargo.setText("Caja");

        reservasQuitarCargo.setText("Cierre de Caja");

        reservasCobroParcial.setText("Cierre nocturno");

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRACION");

        javax.swing.GroupLayout panelFacturacionLayout = new javax.swing.GroupLayout(panelFacturacion);
        panelFacturacion.setLayout(panelFacturacionLayout);
        panelFacturacionLayout.setHorizontalGroup(
            panelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturacionLayout.createSequentialGroup()
                .addGroup(panelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(reservasCobroParcial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reservasQuitarCargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reservasAniadirCargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bloquearHabitaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelFacturacionLayout.setVerticalGroup(
            panelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturacionLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bloquearHabitaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservasAniadirCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservasQuitarCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservasCobroParcial)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        add(panelFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bloquearHabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloquearHabitacionesMouseClicked
       
    }//GEN-LAST:event_bloquearHabitacionesMouseClicked

    private void bloquearHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloquearHabitacionesActionPerformed
            BloquearHabitaciones frame = new BloquearHabitaciones();
            frame.dispose();
            frame.setVisible(true);
    }//GEN-LAST:event_bloquearHabitacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bloquearHabitaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelFacturacion;
    private javax.swing.JButton reservasAniadirCargo;
    private javax.swing.JButton reservasCobroParcial;
    private javax.swing.JButton reservasQuitarCargo;
    // End of variables declaration//GEN-END:variables
}
