package interfaces;

import com.clases.Habitacion;
import com.clases.SystemManager;
import interfaces.panelHabitaciones.ElementoHabitacion;
import interfaces.panelOpciones.PanelAdministracion;
import interfaces.panelOpciones.PanelFacturacion;
import interfaces.panelOpciones.PanelRecepcion;
import interfaces.panelOpciones.PanelReservas;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lucas
 */
public class Application extends javax.swing.JFrame {
    private PanelAdministracion pAdmin=new PanelAdministracion();
    private PanelRecepcion pRecepcion= new PanelRecepcion();
    private PanelFacturacion pFacturacion= new PanelFacturacion();
    private PanelReservas pReservas= new PanelReservas();
    
    
    public Application() {
        initComponents();
        
        SystemManager.centerApp(this);
        
        // Inicializado de systemManager y cargado de habitaciones
        cargarHab(SystemManager.getHabitaciones());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        recepcion = new javax.swing.JButton();
        reservas = new javax.swing.JButton();
        facturacion = new javax.swing.JButton();
        administracion = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        panelOpciones = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        panelHabitaciones = new javax.swing.JPanel();

        jPanel2.setBackground(java.awt.Color.black);
        jPanel2.setPreferredSize(new java.awt.Dimension(75, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));

        background.setBackground(java.awt.Color.black);
        background.setMinimumSize(new java.awt.Dimension(800, 700));
        background.setPreferredSize(new java.awt.Dimension(800, 700));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(80, 105, 140));
        leftPanel.setToolTipText("");
        leftPanel.setMinimumSize(new java.awt.Dimension(200, 700));
        leftPanel.setPreferredSize(new java.awt.Dimension(200, 700));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(196, 221, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SG Hoteles");
        leftPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 188, -1));
        leftPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 200, 10));

        recepcion.setText("RECEPCION");
        recepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarRecepcion(evt);
            }
        });
        leftPanel.add(recepcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 200, -1));

        reservas.setText("RESERVAS");
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarReservas(evt);
            }
        });
        leftPanel.add(reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 200, -1));

        facturacion.setText("FACTURACION");
        facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarFacturacion(evt);
            }
        });
        leftPanel.add(facturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 200, -1));

        administracion.setText("ADMINISTRACION");
        administracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAdministracion(evt);
            }
        });
        leftPanel.add(administracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, 200, -1));

        cerrarSesion.setText("Cerrar sesion");
        leftPanel.add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 200, -1));

        panelOpciones.setBackground(new java.awt.Color(80, 105, 140));
        panelOpciones.setPreferredSize(new java.awt.Dimension(200, 300));

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        leftPanel.add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 209, 200, -1));
        leftPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 185, 200, 18));

        background.add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelHabitaciones.setBackground(java.awt.Color.gray);
        panelHabitaciones.setMinimumSize(new java.awt.Dimension(600, 700));
        panelHabitaciones.setPreferredSize(new java.awt.Dimension(600, 700));
        background.add(panelHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarAdministracion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAdministracion
        mostrarPanel(pAdmin);
    }//GEN-LAST:event_mostrarAdministracion

    private void mostrarFacturacion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarFacturacion
        mostrarPanel(pFacturacion);
    }//GEN-LAST:event_mostrarFacturacion

    private void mostrarReservas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarReservas
        mostrarPanel(pReservas);
    }//GEN-LAST:event_mostrarReservas

    private void mostrarRecepcion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarRecepcion
        mostrarPanel(pRecepcion);
    }//GEN-LAST:event_mostrarRecepcion

    private void mostrarPanel(JPanel panel){
        panelOpciones.removeAll();
        panel.setSize(200,300);
        panel.setLocation(0,0);
        panelOpciones.add(panel);
        panelOpciones.revalidate();
        panelOpciones.repaint();
        panelOpciones.setVisible(false);
        panelOpciones.setVisible(true);
    }
    public void cargarHab(List<Habitacion> habitaciones){
        panelHabitaciones.removeAll();
        for(Habitacion hab: habitaciones){
            panelHabitaciones.add(new ElementoHabitacion(hab));
        }
        panelHabitaciones.revalidate();
        panelHabitaciones.repaint();
        panelHabitaciones.setVisible(false);
        panelHabitaciones.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administracion;
    private javax.swing.JPanel background;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton facturacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel panelHabitaciones;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JButton recepcion;
    private javax.swing.JButton reservas;
    // End of variables declaration//GEN-END:variables
}
